import {
  gameAges,
  gameBallGlow,
  gameClockwork,
  gameDoubleRingedOrb,
  gameDustCloud,
  gameEarthWorm,
  gameEmerald,
  gameExitDoor,
  gameGlassBall,
  gameGlassHeart,
  gameGooeyImpact,
  gameHumanTarget,
  gameIceCube,
  gameMedievalGate,
  gamePauseButton,
  gamePlainCircle,
  gamePlayButton,
  gameSevenPointedStar,
  gameSmallFire,
  gameStonePile,
  gameSwanBreeze,
  gameSwapBag,
  gameSwordBrandish,
  gameVibratingShield,
  gameWorld,
} from '@ng-icons/game-icons';
import {
  tablerCheck,
  tablerPlus,
  tablerSettings,
  tablerX,
} from '@ng-icons/tabler-icons';

export const ALL_ICONS = {
  gameExitDoor,
  gameHumanTarget,
  gameAges,
  gameGooeyImpact,
  gameGlassHeart,
  gameClockwork,
  gameVibratingShield,
  gamePauseButton,
  gamePlayButton,
  gameSmallFire,
  gameIceCube,
  gameSwanBreeze,
  gameStonePile,
  gamePlainCircle,
  gameSevenPointedStar,
  gameSwordBrandish,
  gameSwapBag,
  gameGlassBall,
  gameEmerald,
  gameDoubleRingedOrb,
  gameBallGlow,
  gameEarthWorm,
  gameMedievalGate,
  gameDustCloud,
  gameWorld,
  tablerPlus,
  tablerSettings,
  tablerX,
  tablerCheck,
};
